### ISSUE TITLE
Language and framework

### ISSUE THREAD

**Issue by tcoupin** [IQSS/doi2pmh-server#3]
I was thinking to PHP and http://www.slimframework.com/

**Comment by RightInTwo** [comment]
I would be fine with php. But I think one interesting aspect is the use of existing libs, for example:

python:
- [Python API wrapper for the DataCite Metadata Store API](https://github.com/inveniosoftware/datacite)
- [A python library that implements the Crossref API](https://github.com/fabiobatalha/crossrefapi)
- to be continued....

php:
- to be continued....

javascript:
- to be continued....

**Comment by tcoupin** [comment]
python:
- [Python API wrapper for the DataCite Metadata Store API](https://github.com/inveniosoftware/datacite)
- [A python library that implements the Crossref API](https://github.com/fabiobatalha/crossrefapi)
- to be continued....

php:

* slimframework: routing, middleware (user) http://www.slimframework.com/
* doctrine (database)
* oai-pmh  https://packagist.org/packages/picturae/oai-pmh

js, css:

* [bootstrap ?](https://getbootstrap.com)

**Comment by RightInTwo** [comment]
https://www.openarchives.org/pmh/tools/

**Comment by pdurbin** [comment]
@tcoupin if you ever want an empty repo called dataverse-client-php to push code to (similar to the ones for javascript, r, python, and java), please just let me know! 😄

**Comment by RightInTwo** [comment]
#6 is related

**Comment by RightInTwo** [comment]
Could we use this OAI-PMH server? It is also based on Symfony, just like the great basic application @tcoupin pushed to master.

https://github.com/naoned/OaiPmhServerBundle
> 
> **Features**
>     Compliant with official Oai-Pmh tech spec : http://www.openarchives.org/OAI/openarchivesprotocol.html
>     Sucessfully pass http://re.cs.uct.ac.za/ test
>     Automated resumption in large list, with arrays or ArrayObject
>     On the fly XML generation, if you provide Records in a real-time data-accesing ArrayObject
>     Parametrable resumption items-per-page (default at 50)
> 
> **Limitations**
>     Does not supports resumption (by token) on set lists
>     More data formats (currently supports Dublin Core only)

**Comment by tcoupin** [comment]
This bundle is made for Symfony v2 or v3, doi2pmh use the latest v5, to try...
