### ISSUE TITLE
Docker / Kubernetes support

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/doi2pmh-server#7]
Hey guys,
would you like me to add support for a dockerized installation and Kubernetes objects at IQSS/dataverse-kubernetes?

I'd be willing to contribute:
- Container image (Dockerfile)
- Building & Pushing (Docker Hub, Jenkinsfile, job at jenkins.dataverse.org)
- K8s deployment objects + deps
- Documentation on usage in Cloud & Container guide

**Comment by RightInTwo** [comment]
Hi @poikilotherm, that is really a very nice offer by you! @tcoupin, what do you think?
